FROM fluent/fluentd-kubernetes-daemonset:v1-debian-elasticsearch

# RUN gem install fluent-plugin-kubernetes_metadata_filter
# RUN gem install fluent-plugin-elasticsearch
RUN gem install fluent-plugin-s3
RUN gem install fluent-plugin-logzio