apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: stride-logging
  release: dev
namespace: ops-pr-webhook
resources:
  - ../../base
images:
  - name: stride-logging
    newName: 938631482679.dkr.ecr.us-west-1.amazonaws.com/stride-logging:latest
configMapGenerator:
  - name: fluent-conf
    files:
      - fluentdConfs/fluent.conf
      - fluentdConfs/pods.conf
      - fluentdConfs/elasticsearch.conf
      - fluentdConfs/s3.conf
