apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: stride-logging
  release: local
namespace: stride-logging
resources:
  - ../../base
images:
  - name: stride-logging
    newName: saugat/logging
configMapGenerator:
  - name: fluent-conf
    files:
      - fluentdConfs/fluent.conf
