apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: stride-logging
  release: local
namespace: ops-pr-webhook
resources:
  - ../../base
images:
  - name: stride-logging
    newName: saugat/logging
configMapGenerator:
  - name: fluent-conf
    files:
      - fluentdConfs/fluent.conf
      - fluentdConfs/pods.conf
      - fluentdConfs/elasticsearch.conf
      - fluentdConfs/s3.conf
