apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: stride-logging
  release: dev
namespace: ops-pr-webhook
resources:
  - ../../base
images:
  - name: elasticsearch
    newName: elasticsearch:7.9.1
